import { createApp } from './app.js';

const app = createApp({
  screens: {
    menu: document.getElementById('screen-menu'),
    loading: document.getElementById('screen-loading'),
    playing: document.getElementById('screen-playing'),
    result: document.getElementById('screen-result'),
  },
  progressFill: document.getElementById('progress-fill'),
  progressLabel: document.getElementById('progress-label'),
  canvas: document.getElementById('game-canvas'),
  waveHud: document.getElementById('wave-hud'),
  hpHud: document.getElementById('hp-hud'),
  baseHud: document.getElementById('base-hud'),
  ammoHud: document.getElementById('ammo-hud'),
  promptHud: document.getElementById('prompt-hud'),
  hotbarEl: document.getElementById('hotbar'),
  resultTitle: document.getElementById('result-title'),
  resultDetail: document.getElementById('result-detail'),
  resultStats: document.getElementById('result-stats'),
  btnStart: document.getElementById('btn-start'),
  btnRestore: document.getElementById('btn-restore'),
  btnClearSnap: document.getElementById('btn-clear-snap'),
  snapStatus: document.getElementById('snap-status'),
  saveDropZone: document.getElementById('save-drop-zone'),
  saveFileInput: document.getElementById('save-file-input'),
  saveFileStatus: document.getElementById('save-file-status'),
  btnResultMenu: document.getElementById('btn-result-menu'),
  btnForceWin: document.getElementById('btn-force-win'),
  btnForceLose: document.getElementById('btn-force-lose'),
  btnFreeCraft: document.getElementById('btn-free-craft'),
  btnManualSave: document.getElementById('btn-manual-save'),
  btnMeleeVol: document.getElementById('btn-melee-vol'),
  btnCheat: document.getElementById('btn-cheat'),
  cheatPanel: document.getElementById('panel-cheat'),
  cheatClose: document.getElementById('cheat-close'),
  cheatZoomRange: document.getElementById('cheat-zoom-range'),
  cheatZoomIn: document.getElementById('cheat-zoom-in'),
  cheatZoomOut: document.getElementById('cheat-zoom-out'),
  cheatZoomValue: document.getElementById('cheat-zoom-value'),
  btnJoin: document.getElementById('btn-join'),
  selMode: document.getElementById('sel-mode'),
  roomCodeEl: document.getElementById('room-code'),
  joinStubEl: document.getElementById('join-stub'),
  btnCraft: document.getElementById('btn-craft'),
  craftPanel: document.getElementById('panel-craft'),
  craftTabs: document.getElementById('craft-tabs'),
  craftList: document.getElementById('craft-list'),
  craftStatus: document.getElementById('craft-status'),
  craftClose: document.getElementById('craft-close'),
  receivePanel: document.getElementById('panel-receive'),
  receiveTitle: document.getElementById('receive-title'),
  receiveBody: document.getElementById('receive-body'),
  receiveStatus: document.getElementById('receive-status'),
  receiveClose: document.getElementById('receive-close'),
});

window.__wantToPlay = app;
